name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies 📥
        run: pnpm install

      - name: Build Frontend 🔧
        run: pnpm --filter frontend build:prod

      - name: Prepare Deploy Directory 🔨
        run: |
          mkdir deploy
          cp packages/frontend/index.html deploy/
          cp packages/frontend/style.css deploy/
          cp -r packages/frontend/dist deploy/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          CLEAN: true # Automatically remove deleted files from the deploy branch
